# Generated by Django 4.0.1 on 2022-06-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0005_auto_20220302_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='total_salary',
            field=models.FloatField(default=0),
        ),
    ]
